### ISSUE TITLE
Tips 

### ISSUE THREAD

**Issue by bellaabdelouahab** [devyassin/UpCoders#1]
Hey I like your project,
I would like to contribute with you little bit

Here are some tips to help you :
- new contributers wouldn't want to keep asking you about details about your project and what you need them to do, so the right approach is to create issues for tasks so people know what you need them to do ( also try to label the issues with good-first-issue label it will help you reach more people ) 
- create a contribute.md to help people know what are your guide lines
@devyassin

**Comment by devyassin** [comment]
Hi @bellaabdelouahab ,

Thank you so much i will try to follow ur tips and  advices !
